version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: [dependencies]

  - package-ecosystem: npm
    directory: /console
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: [dependencies, console]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, docker]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
