// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 NestFleet contributors
// This file is part of NestFleet — https://github.com/nestfleet/nestfleet

/**
 * AI Disclosure Templates — CG-01.
 *
 * Channel-aware AI disclosure text for end-user-facing communication.
 * Required by EU AI Act transparency obligation (effective August 2, 2026).
 *
 * Templates are:
 *   - Configurable per product (stored in products.agent_config.disclosure_templates)
 *   - Locale-aware (en, de)
 *   - Channel-aware (email, telegram, web)
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export type DisclosureChannel = "email" | "telegram" | "slack" | "web" | "github"
export type DisclosureContext = "auto_reply" | "clarification" | "resolution" | "notification"
export type DisclosureLocale  = "en" | "de"

export interface DisclosureOptions {
  channel:      DisclosureChannel
  context:      DisclosureContext
  productName:  string
  locale?:      DisclosureLocale
}

export interface DisclosureText {
  header: string
  footer: string
}

export interface DisclosureTemplates {
  [locale: string]: {
    auto_reply_header?:    string
    auto_reply_footer?:    string
    clarification_header?: string
    clarification_footer?: string
    resolution_header?:    string
    resolution_footer?:    string
  }
}

// ── Default templates ─────────────────────────────────────────────────────────

const DEFAULTS: Record<DisclosureLocale, Record<DisclosureContext, { header: string; footer: string }>> = {
  en: {
    auto_reply: {
      header: "This message was generated by an AI assistant on behalf of {productName}.",
      footer: "This response was drafted by AI and may have been reviewed by our support team. If you need human assistance, please reply with 'HUMAN' and a team member will respond.",
    },
    clarification: {
      header: "This is an automated follow-up from {productName}.",
      footer: "This message was generated by AI to help us better understand your request. A team member will review the conversation.",
    },
    resolution: {
      header: "",
      footer: "This case was resolved with AI assistance. Your feedback helps us improve — simply reply to this message.",
    },
    notification: {
      header: "",
      footer: "",
    },
  },
  de: {
    auto_reply: {
      header: "Diese Nachricht wurde von einem KI-Assistenten im Auftrag von {productName} erstellt.",
      footer: "Diese Antwort wurde von einer KI verfasst und möglicherweise von unserem Support-Team überprüft. Wenn Sie menschliche Unterstützung benötigen, antworten Sie bitte mit 'MENSCH'.",
    },
    clarification: {
      header: "Dies ist eine automatisierte Nachverfolgung von {productName}.",
      footer: "Diese Nachricht wurde von einer KI erstellt, um Ihre Anfrage besser zu verstehen. Ein Teammitglied wird das Gespräch überprüfen.",
    },
    resolution: {
      header: "",
      footer: "Dieser Fall wurde mit KI-Unterstützung gelöst. Ihr Feedback hilft uns, uns zu verbessern — antworten Sie einfach auf diese Nachricht.",
    },
    notification: {
      header: "",
      footer: "",
    },
  },
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Get disclosure text for a given channel, context, and locale.
 *
 * @param options   - channel, context, productName, locale
 * @param overrides - optional per-product template overrides from agent_config.disclosure_templates
 */
export function getDisclosure(
  options: DisclosureOptions,
  overrides?: DisclosureTemplates | null,
): DisclosureText {
  const locale = options.locale ?? "en"
  const ctx    = options.context

  // Internal notifications don't need disclosure
  if (ctx === "notification") {
    return { header: "", footer: "" }
  }

  // Check for product-specific overrides first
  const localeOverrides = overrides?.[locale]
  const headerKey = `${ctx}_header` as keyof typeof localeOverrides
  const footerKey = `${ctx}_footer` as keyof typeof localeOverrides

  const rawHeader = localeOverrides?.[headerKey] ?? DEFAULTS[locale]?.[ctx]?.header ?? DEFAULTS.en[ctx].header
  const rawFooter = localeOverrides?.[footerKey] ?? DEFAULTS[locale]?.[ctx]?.footer ?? DEFAULTS.en[ctx].footer

  return {
    header: interpolate(rawHeader, options),
    footer: interpolate(rawFooter, options),
  }
}

/**
 * Wrap a message body with AI disclosure header and footer.
 * Returns the full message text with disclosure applied.
 */
export function applyDisclosure(
  body: string,
  options: DisclosureOptions,
  overrides?: DisclosureTemplates | null,
): string {
  const { header, footer } = getDisclosure(options, overrides)
  const parts: string[] = []

  if (header) parts.push(header, "")
  parts.push(body)
  if (footer) parts.push("", "---", footer)

  return parts.join("\n")
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function interpolate(template: string, options: DisclosureOptions): string {
  return template.replace(/\{productName\}/g, options.productName)
}
