/**                                                                                                                                                                                                                                                                                               
   * GitHub webhook route — POST /webhooks/github/events/:productId                                                                                                                                                                                                                                 
   *                                                                                                                                                                                                                                                                                                
   * Validates X-Hub-Signature-256 when GITHUB_WEBHOOK_SECRET is configured.                                                                                                                                                                                                                      
   * Returns 200 for all accepted events (GitHub expects 200 for everything it delivers).                                                                                                                                                                                                           
   */                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                    
  import { Hono } from "hono"                                                                                                                                                                                                                                                                       
  import { logger } from "../../shared/logger.js"                                                                                                                                                                                                                                                 
  import { config } from "../../shared/config.js"                                                                                                                                                                                                                                                   
  import { decryptSecret } from "../../shared/crypto.js"                                                                                                                                                                                                                                           
  import { validateGitHubWebhook } from "../../infra/github/webhook-validator.js"                                                                                                                                                                                                                   
  import { findProductById } from "../../infra/db/repositories/products.js"                                                                                                                                                                                                                         
   
  interface CiConfig {                                                                                                                                                                                                                                                                              
    enabled: boolean                                                                                                                                                                                                                                                                              
    github_webhook_secret?: string                                                                                                                                                                                                                                                                  
    auto_complete_on_ci_pass: boolean                                                                                                                                                                                                                                                             
    track_deployments: boolean                                                                                                                                                                                                                                                                      
  }                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                    
  export const githubWebhookRouter = new Hono()                                                                                                                                                                                                                                                     
   
  githubWebhookRouter.post("/events/:productId", async (c) => {                                                                                                                                                                                                                                     
    const productId = c.req.param("productId")                                                                                                                                                                                                                                                    
    const eventType = c.req.header("X-GitHub-Event") ?? "unknown"                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                    
    // Raw body needed for HMAC — read once up front                                                                                                                                                                                                                                                
    const rawBody = await c.req.text()                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                    
    // Prefer the per-product secret from ci_config, fall back to global env var.                                                                                                                                                                                                                   
    let webhookSecret = config.GITHUB_WEBHOOK_SECRET                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                    
    // Load product ci_config for per-product secret and automation flags                                                                                                                                                                                                                           
    let ciConfig: CiConfig | null = null                                                                                                                                                                                                                                                            
    try {                                                                                                                                                                                                                                                                                           
      const product = await findProductById(productId)                                                                                                                                                                                                                                            
      if (product) {                                                                                                                                                                                                                                                                               
        const raw = (product.ci_config ?? {}) as Record<string, unknown>                                                                                                                                                                                                                            
        ciConfig = {                                                                                                                                                                                                                                                                                  
          enabled: raw["enabled"] !== false,                                                                                                                                                                                                                                                        
          auto_complete_on_ci_pass: raw["auto_complete_on_ci_pass"] === true,                                                                                                                                                                                                                       
          track_deployments: raw["track_deployments"] === true,                                                                                                                                                                                                                                       
        }                                                                                                                                                                                                                                                                                             
        if (typeof raw["github_webhook_secret"] === "string") {                                                                                                                                                                                                                                   
          ciConfig.github_webhook_secret = raw["github_webhook_secret"]                                                                                                                                                                                                                             
          webhookSecret = decryptSecret(raw["github_webhook_secret"] as string) ?? webhookSecret                                                                                                                                                                                                   
        }                                                                                                                                                                                                                                                                                             
      }                                                                                                                                                                                                                                                                                               
    } catch (err) {                                                                                                                                                                                                                                                                                 
      logger.warn({ err, productId }, "GitHub webhook: failed to load product ci_config (non-fatal)")                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                               
   
    // Reject unsigned requests — webhook secret is required                                                                                                                                                                                                                                        
    if (!webhookSecret) {                                                                                                                                                                                                                                                                         
      logger.warn({ productId, eventType }, "GitHub webhook: no webhook secret configured — rejecting")                                                                                                                                                                                             
      return c.json({ error: "Webhook secret not configured. Set GITHUB_WEBHOOK_SECRET or configure ci_config.github_webhook_secret for this product." }, 403)                                                                                                                                      
    }                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                    
    const signature = c.req.header("X-Hub-Signature-256")                                                                                                                                                                                                                                           
    if (!signature) {                                                                                                                                                                                                                                                                             
      logger.warn({ productId, eventType }, "GitHub webhook: missing X-Hub-Signature-256 header")                                                                                                                                                                                                   
      return c.json({ error: "Missing signature header" }, 400)                                                                                                                                                                                                                                   
    }                                                                                                                                                                                                                                                                                               
   
    const valid = validateGitHubWebhook(rawBody, signature, webhookSecret)                                                                                                                                                                                                                          
    if (!valid) {                                                                                                                                                                                                                                                                                 
      logger.warn({ productId, eventType }, "GitHub webhook: invalid signature")
      return c.json({ error: "Invalid webhook signature" }, 400)                                                                                                                                                                                                                                    
    }
                                                                                                                                                                                                                                                                                                    
    // Parse and dispatch                                                                                                                                                                                                                                                                         
    let payload: unknown
    try {                                                                                                                                                                                                                                                                                           
      payload = JSON.parse(rawBody) as unknown
    } catch {                                                                                                                                                                                                                                                                                       
      return c.json({ error: "Invalid JSON body" }, 400)                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                                                                               
   
    return dispatchEvent(c, productId, eventType, payload, ciConfig)                                                                                                                                                                                                                                
  })