import type { Metadata } from "next"
import { DocsLayout } from "@/components/docs/DocsLayout"

export const metadata: Metadata = {
  title: "Change Requests — NestFleet Docs",
  description: "Manage proposed code and configuration changes with NestFleet's change request workflow.",
}

export default function ChangeRequestsPage() {
  return (
    <DocsLayout
      prev={{ label: "AI Auto-Reply", href: "/docs/user-guide/auto-reply" }}
      next={{ label: "Knowledge Base", href: "/docs/user-guide/knowledge-base" }}
    >
      <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight mb-2">
        Change Requests
      </h1>
      <p className="text-gray-600 leading-relaxed mb-6 text-base">
        A <strong>Change Request</strong> (CR) is a formal record of a proposed code or configuration change,
        created when a case identifies a novel bug or a recurring issue that requires an engineering fix.
        NestFleet drafts the change proposal — including a GitHub PR description, affected surfaces, and a
        risk assessment — and routes it through an approval workflow before any code changes are made.
      </p>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">What a change request is</h2>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        Change requests bridge the gap between customer-facing support and engineering. Rather than
        informally filing a GitHub issue and hoping it gets prioritised, NestFleet creates a structured,
        audited record that captures:
      </p>
      <ul className="list-disc pl-6 text-gray-600 space-y-1 mb-4 text-sm leading-relaxed">
        <li>The originating support case (with full context and customer conversation)</li>
        <li>A proposed fix description generated by the LLM based on the case and codebase context</li>
        <li>Affected surfaces (API, console, worker, database schema)</li>
        <li>Risk assessment: breaking change? Data migration required? Rollback plan?</li>
        <li>The approver&apos;s rationale and decision</li>
        <li>The linked GitHub PR (once implemented)</li>
        <li>A full audit trail of every state transition</li>
      </ul>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">Change request lifecycle</h2>
      <table className="w-full text-sm border-collapse mb-6">
        <thead>
          <tr>
            <th className="text-left bg-gray-50 px-3 py-2 border border-gray-200 font-semibold text-gray-700 w-[160px]">State</th>
            <th className="text-left bg-gray-50 px-3 py-2 border border-gray-200 font-semibold text-gray-700">Meaning</th>
          </tr>
        </thead>
        <tbody>
          {[
            ["draft", "The CR has been created from a case but the AI analysis has not yet run. The change-prep job is enqueued."],
            ["analysis", "The LLM is analysing the case and generating the PR draft, affected surfaces, and risk assessment."],
            ["approval-pending", "Analysis is complete. A Change Lead must review and approve or reject the CR."],
            ["approved", "The Change Lead has approved the CR. An engineer can now implement the change. A GitHub PR is ready to be created."],
            ["rejected", "The Change Lead rejected the CR. The originating case is notified and moves to awaiting-lead for manual handling."],
            ["implemented", "The linked GitHub PR has been merged. The CR is closed. The originating case can now be resolved."],
          ].map(([state, desc]) => (
            <tr key={state}>
              <td className="px-3 py-2 border border-gray-200 align-top font-mono text-xs text-indigo-700 bg-indigo-50">{state}</td>
              <td className="px-3 py-2 border border-gray-200 text-gray-600 align-top">{desc}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">How a change request is created</h2>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        Change requests are always created from a case. There are two paths:
      </p>
      <ol className="list-decimal pl-6 text-gray-600 space-y-2 mb-4 text-sm leading-relaxed">
        <li>
          <strong>Automatic — novel bug detection</strong>: After triage, if the case is classified as a{" "}
          <code className="bg-gray-100 px-1 rounded text-xs">bug</code> and the known-issue search returns no close matches
          (no known issue similarity above the novelty threshold), the system automatically creates a draft CR
          and enqueues the <code className="bg-gray-100 px-1 rounded text-xs">change_prep</code> job.
        </li>
        <li>
          <strong>Manual — team-initiated</strong>: Any team member with the Operator or Support Lead role
          can create a CR from any open case by clicking <strong>Create Change Request</strong> in the case detail view.
          This is useful for feature requests or recurring issues that don&apos;t meet the automatic threshold.
        </li>
      </ol>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">The PR draft</h2>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        When the <code className="bg-gray-100 px-1 rounded text-xs">change_prep</code> job runs, NestFleet uses the complex LLM
        tier to generate a structured GitHub PR draft. The draft includes:
      </p>
      <ul className="list-disc pl-6 text-gray-600 space-y-1 mb-4 text-sm leading-relaxed">
        <li><strong>Title</strong> — a concise, conventional-commit-style PR title</li>
        <li><strong>Problem statement</strong> — a clear description of the bug or gap, grounded in the customer&apos;s report</li>
        <li><strong>Proposed solution</strong> — a high-level description of the fix (not implementation code)</li>
        <li><strong>Affected surfaces</strong> — which parts of the system are touched (e.g. API route, DB migration, console UI)</li>
        <li><strong>Risk assessment</strong> — breaking change risk (none / low / medium / high), data migration required (yes/no), suggested rollback approach</li>
        <li><strong>Test checklist</strong> — what tests should be written or updated</li>
      </ul>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        Once approved, the Change Lead or engineer can push the PR draft to GitHub as a pull request with
        the <strong>Push to GitHub</strong> button. NestFleet uses the configured GitHub App to open the PR
        in the product&apos;s repository with the draft text pre-filled.
      </p>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">Approval workflow</h2>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        Only users with the <strong>Change Lead</strong> role can approve or reject change requests. This
        separation of duties ensures that AI-generated change proposals always pass through a qualified
        human reviewer before any code work begins.
      </p>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        To approve a CR:
      </p>
      <ol className="list-decimal pl-6 text-gray-600 space-y-1 mb-4 text-sm leading-relaxed">
        <li>Open the CR from the Change Requests list or from the originating case</li>
        <li>Review the PR draft, affected surfaces, and risk assessment</li>
        <li>Enter an optional rationale note (required if rejecting)</li>
        <li>Click <strong>Approve</strong> or <strong>Reject</strong></li>
      </ol>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        The approval decision, rationale, and approver identity are recorded as an audit event with
        a timestamp. This creates a permanent, tamper-evident record of who decided what and why.
      </p>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">Rejection</h2>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        When a Change Lead rejects a CR:
      </p>
      <ul className="list-disc pl-6 text-gray-600 space-y-1 mb-4 text-sm leading-relaxed">
        <li>The CR state moves to <code className="bg-gray-100 px-1 rounded text-xs">rejected</code></li>
        <li>The originating support case receives a note with the rejection rationale and moves to <code className="bg-gray-100 px-1 rounded text-xs">awaiting-lead</code></li>
        <li>An audit event is logged</li>
        <li>The team member who created the CR is notified by email</li>
      </ul>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        A rejected CR can be re-submitted after revision if the underlying case changes (e.g. the bug becomes
        more severe or a different root cause is identified).
      </p>

      <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">Infrastructure debt CRs</h2>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        Not all change requests originate from customer cases. NestFleet supports a sidecar CR type for
        infrastructure debt, tagged with <code className="bg-gray-100 px-1 rounded text-xs">cr_track: infra_debt</code>. These are
        created manually by engineers to track security patches, dependency upgrades, or architectural
        improvements that were identified during normal case work but are not tied to a specific customer report.
      </p>
      <p className="text-gray-600 leading-relaxed mb-4 text-sm">
        Infrastructure debt CRs go through the same approval workflow but are listed separately in the
        Change Requests view under the <strong>Infra Debt</strong> tab.
      </p>
    </DocsLayout>
  )
}
